import { idCol, textCol, dateCol, type GridColumn } from "./columns";

export const dynamicColumnsRegistry: Record<number, GridColumn<any>[]> = {
  5: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("MESE", "Mese", { align: "left", width: "w-16" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviate", { align: "left", width: "w-48" }),
    textCol("COD_AZIENDA_UBICAZIONE", "Cod. Azienda Ubic.", { align: "left", width: "w-40" }),
    idCol("ID_RICETTA", "Ricetta #", { align: "left" }),
    textCol("COD_PRESTAZIONE", "Cod. Prestazione", { align: "left" }),
    textCol("FILLER", "Filler", { align: "left" }),
    textCol("CAMPO_ERRATO", "Campo Errato", { align: "left" }),
    textCol("DESC_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ERRORE", "Cod. Errore", { align: "left", width: "w-20" }),
    textCol("DESC_ERRORE", "Descr. Errore", { align: "left", width: "w-64" }),
    textCol("VALORE_CAMPO", "Valore Campo", { align: "left", width: "w-64" }),
  ],
  46: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("MODELLO", "Modello", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIT", "Periodo Rit.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("SPAZIO_VUOTO", "Spazio Vuoto", { align: "left" }),
    textCol("ASL_DI_EROGAZIONE", "ASL di Erogazione", { align: "left", width: "w-48" }),
    idCol("ID_PRESA_CARICO", "Presa Carico #", { align: "left" }),
    textCol("CHIAVE_DEL_RECORD", "Chiave del Record", { align: "left", width: "w-48" }),
    textCol("DESC_CHIAVE_RECORD", "Descr. Chiave Record", { align: "left", width: "w-64" }),
    textCol("STRUTT_PRESA_CARICO", "Strutt. Presa Carico", { align: "left", width: "w-48" }),
    textCol("DENOM_STRUTT_PRESA_CARICO", "Denom. Strutt. Presa Carico", {
      align: "left",
      width: "w-64",
    }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCRIZIONE_CAMPO", "Descrizione Campo", { align: "left", width: "w-64" }),
    textCol("CODICE_ANOMALIA", "Codice Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCRIZIONE_ANOMALIA", "Descrizione Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_DEL_CAMPO", "Valore del Campo", { align: "left", width: "w-64" }),
  ],
  61: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("MODELLO", "Modello", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("MESE", "Mese", { align: "left", width: "w-16" }),
    textCol("AZ_INVITANTE", "Azienda Invitante", { align: "left", width: "w-48" }),
    idCol("PROGR_CO", "Prog. CO", { align: "left" }),
    idCol("PROGR_CHIAM", "Prog. Chiam.", { align: "left" }),
    idCol("PROGR_INTERV", "Prog. Interv.", { align: "left" }),
    dateCol("DATA_INTERV", "Data Interv.", { align: "left", withTime: true }),
    idCol("PROGR_MISS", "Prog. Miss.", { align: "left" }),
    idCol("PROGR_PAZ", "Prog. Paz.", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCR_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ANOMALIA", "Cod. Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCR_ANOMALIA", "Descr. Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_CAMPO", "Valore Campo", { align: "left", width: "w-64" }),
  ],
  63: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("MODELLO", "Modello", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("MESE", "Mese", { align: "left", width: "w-16" }),
    textCol("AZ_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    idCol("PROGR_CO", "Prog. CO", { align: "left" }),
    idCol("PROGR_CHIAM", "Prog. Chiam.", { align: "left" }),
    idCol("PROGR_INTERV", "Prog. Interv.", { align: "left" }),
    dateCol("DATA_INTERV", "Data Interv.", { align: "left", withTime: true }),
    idCol("PROGR_MISS", "Prog. Miss.", { align: "left" }),
    idCol("PROGR_PAZ", "Prog. Paz.", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCR_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ANOMALIA", "Cod. Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCR_ANOMALIA", "Descr. Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_CAMPO", "Valore Campo", { align: "left", width: "w-64" }),
  ],
  64: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIT", "Periodo Rit.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("ASL_DI_EROGAZIONE", "ASL di Erogazione", { align: "left", width: "w-48" }),
    idCol("ID_PRESA_CARICO", "Presa Carico #", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCRIZIONE_CAMPO", "Descrizione Campo", { align: "left", width: "w-64" }),
    textCol("CODICE_ANOMALIA", "Codice Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCRIZIONE_ANOMALIA", "Descrizione Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_DEL_CAMPO", "Valore del Campo", { align: "left", width: "w-64" }),
    textCol("STRUTT_PRESA_CARICO", "Strutt. Presa Carico", { align: "left", width: "w-48" }),
    textCol("DENOM_STRUTT_PRESA_CARICO", "Denom. Strutt. Presa Carico", {
      align: "left",
      width: "w-64",
    }),
    textCol("FLAG_INVIO_NSIS", "Flag Invio NSIS", { align: "left", width: "w-32" }),
  ],

  65: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIT", "Periodo Rit.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("ASL_DI_EROGAZIONE", "ASL di Erogazione", { align: "left", width: "w-48" }),
    idCol("ID_PRESA_CARICO", "Presa Carico #", { align: "left" }),
    dateCol("DATA_RIVALUTAZIONE", "Data Rivalutazione", { align: "left", withTime: true }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCRIZIONE_CAMPO", "Descrizione Campo", { align: "left", width: "w-64" }),
    textCol("CODICE_ANOMALIA", "Codice Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCRIZIONE_ANOMALIA", "Descrizione Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_DEL_CAMPO", "Valore del Campo", { align: "left", width: "w-64" }),
    textCol("STRUTT_PRESA_CARICO", "Strutt. Presa Carico", { align: "left", width: "w-48" }),
    textCol("DENOM_STRUTT_PRESA_CARICO", "Denom. Strutt. Presa Carico", {
      align: "left",
      width: "w-64",
    }),
    textCol("FLAG_INVIO_NSIS", "Flag Invio NSIS", { align: "left", width: "w-32" }),
  ],

  66: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIT", "Periodo Rit.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("ASL_DI_EROGAZIONE", "ASL di Erogazione", { align: "left", width: "w-48" }),
    idCol("ID_PRESA_CARICO", "Presa Carico #", { align: "left" }),
    dateCol("DATA_CONCLUSIONE", "Data Conclusione", { align: "left", withTime: true }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCRIZIONE_CAMPO", "Descrizione Campo", { align: "left", width: "w-64" }),
    textCol("CODICE_ANOMALIA", "Codice Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCRIZIONE_ANOMALIA", "Descrizione Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_DEL_CAMPO", "Valore del Campo", { align: "left", width: "w-64" }),
    textCol("STRUTT_PRESA_CARICO", "Strutt. Presa Carico", { align: "left", width: "w-48" }),
    textCol("DENOM_STRUTT_PRESA_CARICO", "Denom. Strutt. Presa Carico", {
      align: "left",
      width: "w-64",
    }),
    textCol("FLAG_INVIO_NSIS", "Flag Invio NSIS", { align: "left", width: "w-32" }),
  ],

  67: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIT", "Periodo Rit.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("ASL_DI_EROGAZIONE", "ASL di Erogazione", { align: "left", width: "w-48" }),
    idCol("ID_PRESA_CARICO", "Presa Carico #", { align: "left" }),
    dateCol("DATA_ACCESSO", "Data Accesso", { align: "left", withTime: true }),
    textCol("TIPO_OPERATORE", "Tipo Operatore", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCRIZIONE_CAMPO", "Descrizione Campo", { align: "left", width: "w-64" }),
    textCol("CODICE_ANOMALIA", "Codice Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCRIZIONE_ANOMALIA", "Descrizione Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_DEL_CAMPO", "Valore del Campo", { align: "left", width: "w-64" }),
    textCol("STRUTT_PRESA_CARICO", "Strutt. Presa Carico", { align: "left", width: "w-48" }),
    textCol("DENOM_STRUTT_PRESA_CARICO", "Denom. Strutt. Presa Carico", {
      align: "left",
      width: "w-64",
    }),
    textCol("FLAG_INVIO_NSIS", "Flag Invio NSIS", { align: "left", width: "w-32" }),
    textCol("TIPO_ACCESSO", "Tipo Accesso", { align: "left" }),
  ],

  68: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIT", "Periodo Rit.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("ASL_DI_EROGAZIONE", "ASL di Erogazione", { align: "left", width: "w-48" }),
    idCol("ID_PRESA_CARICO", "Presa Carico #", { align: "left" }),
    dateCol("DATA_ACCESSO", "Data Accesso", { align: "left", withTime: true }),
    textCol("TIPO_OPERATORE", "Tipo Operatore", { align: "left" }),
    textCol("TIPO_PRESTAZIONE", "Tipo Prestazione", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCRIZIONE_CAMPO", "Descrizione Campo", { align: "left", width: "w-64" }),
    textCol("CODICE_ANOMALIA", "Codice Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCRIZIONE_ANOMALIA", "Descrizione Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_DEL_CAMPO", "Valore del Campo", { align: "left", width: "w-64" }),
    textCol("STRUTT_PRESA_CARICO", "Strutt. Presa Carico", { align: "left", width: "w-48" }),
    textCol("DENOM_STRUTT_PRESA_CARICO", "Denom. Strutt. Presa Carico", {
      align: "left",
      width: "w-64",
    }),
    textCol("FLAG_INVIO_NSIS", "Flag Invio NSIS", { align: "left", width: "w-32" }),
    textCol("TIPO_ACCESSO", "Tipo Accesso", { align: "left" }),
  ],

  69: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIT", "Periodo Rit.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("ASL_DI_EROGAZIONE", "ASL di Erogazione", { align: "left", width: "w-48" }),
    idCol("ID_PRESA_CARICO", "Presa Carico #", { align: "left" }),
    dateCol("DATA_INIZIO_SOSPENSIONE", "Data Inizio Sosp.", { align: "left", withTime: true }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCRIZIONE_CAMPO", "Descrizione Campo", { align: "left", width: "w-64" }),
    textCol("CODICE_ANOMALIA", "Codice Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCRIZIONE_ANOMALIA", "Descrizione Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_DEL_CAMPO", "Valore del Campo", { align: "left", width: "w-64" }),
    textCol("STRUTT_PRESA_CARICO", "Strutt. Presa Carico", { align: "left", width: "w-48" }),
    textCol("DENOM_STRUTT_PRESA_CARICO", "Denom. Strutt. Presa Carico", {
      align: "left",
      width: "w-64",
    }),
    textCol("FLAG_INVIO_NSIS", "Flag Invio NSIS", { align: "left", width: "w-32" }),
  ],

  70: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIT", "Periodo Rit.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("ASL_DI_EROGAZIONE", "ASL di Erogazione", { align: "left", width: "w-48" }),
    idCol("ID_PRESA_CARICO", "Presa Carico #", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESCRIZIONE_CAMPO", "Descrizione Campo", { align: "left", width: "w-64" }),
    textCol("CODICE_ANOMALIA", "Codice Anomalia", { align: "left", width: "w-20" }),
    textCol("DESCRIZIONE_ANOMALIA", "Descrizione Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_DEL_CAMPO", "Valore del Campo", { align: "left", width: "w-64" }),
    textCol("STRUTT_PRESA_CARICO", "Strutt. Presa Carico", { align: "left", width: "w-48" }),
    textCol("DENOM_STRUTT_PRESA_CARICO", "Denom. Strutt. Presa Carico", {
      align: "left",
      width: "w-64",
    }),
    textCol("FLAG_INVIO_NSIS", "Flag Invio NSIS", { align: "left", width: "w-32" }),
  ],
  80: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("TRIM", "Trimestre", { align: "left", width: "w-20" }),
    textCol("GESTORE", "Gestore", { align: "left", width: "w-48" }),
    idCol("NUM_PRATICA", "Num. Pratica", { align: "left" }),
    idCol("PROGRESSIVO", "Progressivo", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESC_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ANOMALIA", "Cod. Anomalia", { align: "left", width: "w-20" }),
    textCol("DESC_ANOMALIA", "Descr. Anomalia", { align: "left", width: "w-64" }),
    idCol("ID_RECORD", "Record # (dup)", { align: "left", width: "w-28" }),
  ],

  81: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("PERIODO_RIF", "Periodo Rif.", { align: "left" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("PRESIDIO_EROG_CODICE_STRUTT", "Presidio Erog. Cod. Strutt.", {
      align: "left",
      width: "w-64",
    }),
    idCol("ID_PRESA_CARICO_ID_SEGN", "Presa Carico/Segn. #", { align: "left" }),
    textCol("MODELLO", "Modello", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESC_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ANOMALIA", "Cod. Anomalia", { align: "left", width: "w-20" }),
    textCol("DESC_ANOMALIA", "Descr. Anomalia", { align: "left", width: "w-64" }),
    textCol("VAL_CAMPO", "Valore Campo", { align: "left", width: "w-64" }),
    textCol("FLAG_INVIO_NSIS", "Flag Invio NSIS", { align: "left", width: "w-32" }),
  ],
  83: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("MODELLO", "Modello", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("MESE", "Mese", { align: "left", width: "w-16" }),
    textCol("AZIENDA_INVIANTE", "Azienda Inviante", { align: "left", width: "w-48" }),
    textCol("COD_STRUTTURA", "Cod. Struttura", { align: "left", width: "w-40" }),
    idCol("ID_ACCESSO", "Accesso #", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESC_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ANOMALIA", "Cod. Anomalia", { align: "left", width: "w-20" }),
    textCol("DESC_ANOMALIA", "Descr. Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_CAMPO", "Valore Campo", { align: "left", width: "w-64" }),
  ],

  85: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("MESE", "Mese", { align: "left", width: "w-16" }),
    textCol("COD_STRUTT", "Cod. Strutt.", { align: "left", width: "w-40" }),
    idCol("ID_ACCESSO", "Accesso #", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESC_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ANOMALIA", "Cod. Anomalia", { align: "left", width: "w-20" }),
    textCol("DESC_ANOMALIA", "Descr. Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_CAMPO", "Valore Campo", { align: "left", width: "w-64" }),
  ],

  87: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("MESE", "Mese", { align: "left", width: "w-16" }),
    textCol("COD_STRUTTURA", "Cod. Struttura", { align: "left", width: "w-40" }),
    idCol("ID_ACCESSO", "Accesso #", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESC_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ANOMALIA", "Cod. Anomalia", { align: "left", width: "w-20" }),
    textCol("DESC_ANOMALIA", "Descr. Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_CAMPO", "Valore Campo", { align: "left", width: "w-64" }),
    textCol("ANOMALIA_PRIM", "Anomalia Prim.", { align: "left", width: "w-32" }),
  ],

  89: [
    idCol("ID_RECORD", "Record #", { align: "left", width: "w-28" }),
    dateCol("DATA_INVIO", "Data Invio", { align: "left", withTime: true }),
    textCol("PERIODO", "Periodo", { align: "left" }),
    idCol("INVIO_NUM", "Invio #", { align: "left" }),
    textCol("MODELLO", "Modello", { align: "left" }),
    textCol("ANNO", "Anno", { align: "left", width: "w-16" }),
    textCol("MESE", "Mese", { align: "left", width: "w-16" }),
    textCol("COD_STRUTTURA", "Cod. Struttura", { align: "left", width: "w-40" }),
    idCol("ID_ACCESSO", "Accesso #", { align: "left" }),
    textCol("CAMPO", "Campo", { align: "left" }),
    textCol("DESC_CAMPO", "Descr. Campo", { align: "left", width: "w-48" }),
    textCol("COD_ANOMALIA", "Cod. Anomalia", { align: "left", width: "w-20" }),
    textCol("DESC_ANOMALIA", "Descr. Anomalia", { align: "left", width: "w-64" }),
    textCol("VALORE_CAMPO", "Valore Campo", { align: "left", width: "w-64" }),
  ],
    78: [
    idCol('ID_RECORD', 'Record #', { align: 'left', width: 'w-28' }),
    dateCol('DATA_INVIO', 'Data Invio', { align: 'left', withTime: true }),
    textCol('PERIODO', 'Periodo', { align: 'left' }),
    idCol('INVIO_NUM', 'Invio #', { align: 'left' }),
    textCol('ANNO', 'Anno', { align: 'left', width: 'w-16' }),
    textCol('COD_PERIODO', 'Cod. Periodo', { align: 'left' }),
    textCol('AZIENDA_INVIANTE', 'Azienda Inviante', { align: 'left', width: 'w-48' }),
    textCol('COD_AZIENDA_PRESIDIO', 'Cod. Azienda Presidio', { align: 'left', width: 'w-48' }),
    textCol('COD_STRUTTURA', 'Cod. Struttura', { align: 'left', width: 'w-40' }),
    idCol('ID_RICETTA', 'Ricetta #', { align: 'left' }),
    textCol('COD_PRESCRITTORE', 'Cod. Prescrittore', { align: 'left' }),
    dateCol('DATA_EROGAZIONE', 'Data Erogazione', { align: 'left', withTime: true }),
    textCol('IMPORTO_TOTALE_NETTO', 'Importo Totale Netto', { align: 'left' }),
    textCol('COD_FISCALE', 'Cod. Fiscale', { align: 'left', width: 'w-40' }),
    textCol('MATRICOLA', 'Matricola', { align: 'left' }),
    textCol('COGNOME', 'Cognome', { align: 'left' }),
    textCol('NOME', 'Nome', { align: 'left' }),
    textCol('SESSO', 'Sesso', { align: 'left', width: 'w-16' }),
    dateCol('DATA_NASCITA', 'Data Nascita', { align: 'left' }),
    textCol('COD_COMUNE_RESIDENZA', 'Cod. Comune Residenza', { align: 'left', width: 'w-48' }),
    textCol('USL_APPARTENENZA', 'USL Appartenenza', { align: 'left', width: 'w-48' }),
    dateCol('DATA_INIZIO_ISCRIZIONE', 'Inizio Iscrizione', { align: 'left' }),
    dateCol('DATA_FINE_ISCRIZIONE', 'Fine Iscrizione', { align: 'left' }),
    textCol('COGNOME_MED_BASE', 'Cognome Med. Base', { align: 'left', width: 'w-48' }),
    textCol('NOME_MED_BASE', 'Nome Med. Base', { align: 'left', width: 'w-48' }),
    textCol('SESSO_MED_BASE', 'Sesso Med. Base', { align: 'left', width: 'w-16' }),
    textCol('COD_REGIONE_MED_BASE', 'Cod. Regione Med. Base', { align: 'left', width: 'w-40' }),
    textCol('COD_COMUNE_MED_BASE', 'Cod. Comune Med. Base', { align: 'left', width: 'w-48' }),
    textCol('COD_ASL_MED_BASE', 'Cod. ASL Med. Base', { align: 'left', width: 'w-40' }),
    idCol('ID_COD_FISCALE_MATR', 'Cod. Fiscale Matr. #', { align: 'left' }),
    textCol('AZIENDA_INVIANTE2', 'Azienda Inviante 2', { align: 'left', width: 'w-48' }),
  ],

  77: [
    idCol('ID_RECORD', 'Record #', { align: 'left', width: 'w-28' }),
    dateCol('DATA_INVIO', 'Data Invio', { align: 'left', withTime: true }),
    textCol('PERIODO', 'Periodo', { align: 'left' }),
    idCol('INVIO_NUM', 'Invio #', { align: 'left' }),
    textCol('MODELLO', 'Modello', { align: 'left' }),
    textCol('ANNO', 'Anno', { align: 'left', width: 'w-16' }),
    textCol('MESE', 'Mese', { align: 'left', width: 'w-16' }),
    textCol('AZIENDA_INVIANTE_DSA', 'Azienda Inviante DSA', { align: 'left', width: 'w-64' }),
    textCol('CODICE_STRUTTURA_EROG_DSA', 'Cod. Strutt. Erog. DSA', { align: 'left', width: 'w-64' }),
    idCol('ID_DSA', 'DSA #', { align: 'left' }),
    idCol('ID_RICETTA', 'Ricetta #', { align: 'left' }),
    textCol('COD_STRUTTURA', 'Cod. Struttura', { align: 'left', width: 'w-40' }),
    textCol('RICETTA', 'Ricetta', { align: 'left' }),
    textCol('CAMPO', 'Campo', { align: 'left' }),
    textCol('DESC_CAMPO', 'Descr. Campo', { align: 'left', width: 'w-48' }),
    textCol('COD_ANOMALIA', 'Cod. Anomalia', { align: 'left', width: 'w-20' }),
    textCol('DESC_ANOMALIA', 'Descr. Anomalia', { align: 'left', width: 'w-64' }),
    textCol('VALORE_CAMPO', 'Valore Campo', { align: 'left', width: 'w-64' }),
    textCol('COD_FISCALE', 'Cod. Fiscale', { align: 'left', width: 'w-40' }),
  ],

  76: [
    idCol('ID_RECORD', 'Record #', { align: 'left', width: 'w-28' }),
    dateCol('DATA_INVIO', 'Data Invio', { align: 'left', withTime: true }),
    textCol('PERIODO', 'Periodo', { align: 'left' }),
    idCol('INVIO_NUM', 'Invio #', { align: 'left' }),
    textCol('ANNO', 'Anno', { align: 'left', width: 'w-16' }),
    textCol('MESE', 'Mese', { align: 'left', width: 'w-16' }),
    textCol('AZIENDA_INVIANTE', 'Azienda Inviante', { align: 'left', width: 'w-48' }),
    textCol('COD_AZIENDA_PRESIDIO', 'Cod. Azienda Presidio', { align: 'left', width: 'w-48' }),
    textCol('COD_STRUTTURA', 'Cod. Struttura', { align: 'left', width: 'w-40' }),
    idCol('ID_RICETTA', 'Ricetta #', { align: 'left' }),
    textCol('COD_PRESTAZIONE', 'Cod. Prestazione', { align: 'left' }),
    textCol('CAMPO', 'Campo', { align: 'left' }),
    textCol('DESC_CAMPO', 'Descr. Campo', { align: 'left', width: 'w-48' }),
    textCol('COD_ANOMALIA', 'Cod. Anomalia', { align: 'left', width: 'w-20' }),
    textCol('DESC_ANOMALIA', 'Descr. Anomalia', { align: 'left', width: 'w-64' }),
    textCol('VALORE_CAMPO', 'Valore Campo', { align: 'left', width: 'w-64' }),
    textCol('FLAG_ANOMALIA', 'Flag Anomalia', { align: 'left', width: 'w-32' }),
  ],

  75: [
    idCol('ID_RECORD', 'Record #', { align: 'left', width: 'w-28' }),
    dateCol('DATA_INVIO', 'Data Invio', { align: 'left', withTime: true }),
    textCol('PERIODO', 'Periodo', { align: 'left' }),
    idCol('INVIO_NUM', 'Invio #', { align: 'left' }),
    textCol('ANNO', 'Anno', { align: 'left', width: 'w-16' }),
    textCol('MESE', 'Mese', { align: 'left', width: 'w-16' }),
    textCol('AZIENDA_INVIANTE', 'Azienda Inviante', { align: 'left', width: 'w-48' }),
    textCol('COD_AZIENDA_PRESIDIO', 'Cod. Azienda Presidio', { align: 'left', width: 'w-48' }),
    textCol('COD_STRUTTURA', 'Cod. Struttura', { align: 'left', width: 'w-40' }),
    idCol('ID_RICETTA', 'Ricetta #', { align: 'left' }),
    textCol('COD_PRESTAZIONE', 'Cod. Prestazione', { align: 'left' }),
    textCol('CAMPO', 'Campo', { align: 'left' }),
    textCol('DESC_CAMPO', 'Descr. Campo', { align: 'left', width: 'w-48' }),
    textCol('COD_ANOMALIA', 'Cod. Anomalia', { align: 'left', width: 'w-20' }),
    textCol('DESC_ANOMALIA', 'Descr. Anomalia', { align: 'left', width: 'w-64' }),
    textCol('VALORE_CAMPO', 'Valore Campo', { align: 'left', width: 'w-64' }),
    textCol('FLAG_ANOMALIA', 'Flag Anomalia', { align: 'left', width: 'w-32' }),
  ],

  74: [
    idCol('ID_RECORD', 'Record #', { align: 'left', width: 'w-28' }),
    dateCol('DATA_INVIO', 'Data Invio', { align: 'left', withTime: true }),
    textCol('PERIODO', 'Periodo', { align: 'left' }),
    idCol('INVIO_NUM', 'Invio #', { align: 'left' }),
    textCol('ANNO', 'Anno', { align: 'left', width: 'w-16' }),
    textCol('MESE', 'Mese', { align: 'left', width: 'w-16' }),
    textCol('AZIENDA_INVIANTE', 'Azienda Inviante', { align: 'left', width: 'w-48' }),
    textCol('COD_AZIENDA_PRESIDIO', 'Cod. Azienda Presidio', { align: 'left', width: 'w-48' }),
    textCol('COD_STRUTTURA', 'Cod. Struttura', { align: 'left', width: 'w-40' }),
    idCol('ID_RICETTA', 'Ricetta #', { align: 'left' }),
    textCol('COD_PRESTAZIONE', 'Cod. Prestazione', { align: 'left' }),
    textCol('CAMPO', 'Campo', { align: 'left' }),
    textCol('DESC_CAMPO', 'Descr. Campo', { align: 'left', width: 'w-48' }),
    textCol('COD_ANOMALIA', 'Cod. Anomalia', { align: 'left', width: 'w-20' }),
    textCol('DESC_ANOMALIA', 'Descr. Anomalia', { align: 'left', width: 'w-64' }),
    textCol('VALORE_CAMPO', 'Valore Campo', { align: 'left', width: 'w-64' }),
  ],

  73: [
    idCol('ID_RECORD', 'Record #', { align: 'left', width: 'w-28' }),
    dateCol('DATA_INVIO', 'Data Invio', { align: 'left', withTime: true }),
    textCol('PERIODO', 'Periodo', { align: 'left' }),
    idCol('INVIO_NUM', 'Invio #', { align: 'left' }),
    textCol('MODELLO', 'Modello', { align: 'left' }),
    textCol('ANNO', 'Anno', { align: 'left', width: 'w-16' }),
    textCol('MESE', 'Mese', { align: 'left', width: 'w-16' }),
    textCol('COD_STRUTTURA', 'Cod. Struttura', { align: 'left', width: 'w-40' }),
    idCol('ID_ACCESSO', 'Accesso #', { align: 'left' }),
    textCol('CAMPO', 'Campo', { align: 'left' }),
    textCol('DESC_CAMPO', 'Descr. Campo', { align: 'left', width: 'w-48' }),
    textCol('COD_ANOMALIA', 'Cod. Anomalia', { align: 'left', width: 'w-20' }),
    textCol('DESC_ANOMALIA', 'Descr. Anomalia', { align: 'left', width: 'w-64' }),
    textCol('VALORE_CAMPO', 'Valore Campo', { align: 'left', width: 'w-64' }),
  ],

  72: [
    idCol('ID_RECORD', 'Record #', { align: 'left', width: 'w-28' }),
    dateCol('DATA_INVIO', 'Data Invio', { align: 'left', withTime: true }),
    textCol('PERIODO', 'Periodo', { align: 'left' }),
    idCol('INVIO_NUM', 'Invio #', { align: 'left' }),
    textCol('AZIENDA', 'Azienda', { align: 'left', width: 'w-48' }),
    textCol('COD_STRUTTURA', 'Cod. Struttura', { align: 'left', width: 'w-40' }),
    idCol('ID_RICETTA', 'Ricetta #', { align: 'left' }),
    textCol('IMPORTO_NETTO_MODELLO_S', 'Importo Netto Mod. S', { align: 'left', width: 'w-48' }),
    textCol('SEGNO_IMPORTO_TOT_NETTO_RIC', 'Segno Importo Tot. Netto Ric.', { align: 'left', width: 'w-64' }),
    textCol('IMPORTO_TOTNETTO_RIC', 'Importo Tot. Netto Ric.', { align: 'left', width: 'w-64' }),
    textCol('REG_RESIDENZA', 'Reg. Residenza', { align: 'left', width: 'w-40' }),
    textCol('ASL_RESIDENZA', 'ASL Residenza', { align: 'left', width: 'w-40' }),
    textCol('ANNO_RIFERIMENTO', 'Anno Riferimento', { align: 'left', width: 'w-32' }),
    textCol('PERIODO_RIFERIMENTO', 'Periodo Riferimento', { align: 'left', width: 'w-48' }),
  ],

  71: [
    idCol('ID_RECORD', 'Record #', { align: 'left', width: 'w-28' }),
    dateCol('DATA_INVIO', 'Data Invio', { align: 'left', withTime: true }),
    textCol('PERIODO', 'Periodo', { align: 'left' }),
    idCol('INVIO_NUM', 'Invio #', { align: 'left' }),
    textCol('AZIENDA', 'Azienda', { align: 'left', width: 'w-48' }),
    textCol('COD_STRUTTURA', 'Cod. Struttura', { align: 'left', width: 'w-40' }),
    idCol('ID_RICETTA', 'Ricetta #', { align: 'left' }),
    textCol('IMPORTO_NETTO_MODELLO_S', 'Importo Netto Mod. S', { align: 'left', width: 'w-48' }),
    textCol('SEGNO_IMPORTO_TOT_NETTO_RIC', 'Segno Importo Tot. Netto Ric.', { align: 'left', width: 'w-64' }),
    textCol('IMPORTO_TOT_NETTO_RIC', 'Importo Tot. Netto Ric.', { align: 'left', width: 'w-64' }),
    textCol('REG_RESIDENZA', 'Reg. Residenza', { align: 'left', width: 'w-40' }),
    textCol('ASL_RESIDENZA', 'ASL Residenza', { align: 'left', width: 'w-40' }),
    textCol('ANNO_RIFERIMENTO', 'Anno Riferimento', { align: 'left', width: 'w-32' }),
    textCol('PERIODO_RIFERIMENTO', 'Periodo Riferimento', { align: 'left', width: 'w-48' }),
  ],

};
